import { Campaign } from '@/types/campaign';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    name: 'Promo Ramadhan 2026',
    type: 'WhatsApp',
    sender: 'CS Utama (+62812...)',
    category: 'Promosi',
    message: 'Selamat datang Ramadhan! Dapatkan diskon 50% untuk produk kami.',
    status: 'Sent',
    targetCount: 12500,
    successCount: 12450,
    failCount: 50,
    createdAt: '2026-04-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Dashboard Alert SMS',
    type: 'SMS',
    sender: 'TSEL SMS GW',
    category: 'Notifikasi',
    message: 'Update saldo harian Anda adalah Rp 2.450.000.',
    status: 'Sent',
    targetCount: 5000,
    successCount: 4980,
    failCount: 20,
    createdAt: '2026-04-02T08:30:00Z',
  },
  {
    id: '3',
    name: 'Flash Sale Weekend',
    type: 'WhatsApp',
    sender: 'Marketing A (+62857...)',
    category: 'Promosi',
    message: 'Flash Sale hadir kembali! Hanya akhir pekan ini.',
    status: 'Queued',
    targetCount: 20000,
    successCount: 0,
    failCount: 0,
    createdAt: '2026-04-07T12:00:00Z',
  },
  {
    id: '4',
    name: 'OTP Verification Test',
    type: 'WhatsApp',
    sender: 'CS Utama (+62812...)',
    category: 'Notifikasi',
    message: 'Kode OTP Anda adalah 123456.',
    status: 'Draft',
    targetCount: 1,
    successCount: 0,
    failCount: 0,
    createdAt: '2026-04-07T14:45:00Z',
  }
];
